### PR TITLE
Make configuration template configurable

### PR DESCRIPTION
**Pull request by goetzk**
This minor changes allows overriding the template used in the role to improve
integration with local requirements.

### CODE REVIEW

**Comment by goetzk** [comment]
Forgot to mention - I made this change while considering what to do about #22

**Comment by goetzk** [comment]
Hi @mrlesmithjr ,
Have you had a chance to review this change? Its trivially small and defaults to not changing the exiting behaviour.

thanks,
Karl.

**Review by mrlesmithjr — APPROVED** [review]

**Comment by mrlesmithjr** [comment]
@goetzk Thanks for reminding me of this. Sorry it took so long!

**Comment by goetzk** [comment]
Thanks!

**Pull request merged**
