### PR TITLE
Select which interfaces to enable.

### PR DESCRIPTION
**Pull request by roedie**
Added the 'enable' item so you can select the interface to enable.

### CODE REVIEW

**Comment by mrlesmithjr** [comment]
@roedie Have you done any more testing with this? Wondered if you had any issues or anything. I'd like to look into this and get this merged in if it is still applicable.

**Comment by roedie** [comment]
Yes, I'm using this in production. I didn't have any problems with it so far.

The only thing I had was that an interface got reconfigured after the DNS settings were changed. Looking at the config this was to be expected but it cought me by surprise. It would have happened if I had enabled enable_configured_interfaces_after_defining as well, so I don't consider it a bug on this part ;-)

**Comment by mrlesmithjr** [comment]
@roedie We should probably add the enable parameter as part of the example options in defaults/main.yml as well so it is obvious in regards to options available.

**Comment by roedie** [comment]
Sure, I'll update the PR tonight or later this week.

**Comment by roedie** [comment]
@mrlesmithjr Gosh that took a bit longer than I wanted. I squashed everything into one commit again.

**Comment by mrlesmithjr** [comment]
@roedie Merged! Thanks for this.

**Pull request merged**
